### ISSUE TITLE
Error when passing a list of emails using '*.*'

### ISSUE THREAD

**Issue by ireichman** [ireichman/email_to_pdf#11]
Command used `python main.py -s ~/path/*.* -o ~/path/`

Traceback (most recent call last):
  File "/home/i/git/email_to_pdf/main.py", line 67, in <module>
    pdf_name = pdf_naming(naming_pattern=output_file_name, output_path=path_validated, email_name=email["email_file"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/i/git/email_to_pdf/utils.py", line 46, in pdf_naming
    name = output_path + name
           ~~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

**Comment by ireichman** [comment]
Was passing the results of path validation rather than the path itself. 
Changed the var that is passed to the pdf_naming function to the actual path from argparse or a blank string if none is passed.
